/**
 * generate-env.js
 * Reads the TWELVE_DATA_API_KEY environment variable and writes it into
 * src/environments/environment.key.ts so Angular can compile it in.
 *
 * Run this before `ng build` in CI/CD (e.g. Vercel).
 *   node scripts/generate-env.js
 */

const fs   = require('fs');
const path = require('path');

const apiKey = process.env.TWELVE_DATA_API_KEY || '';

if (!apiKey) {
  console.warn(
    '\u26a0\ufe0f  TWELVE_DATA_API_KEY is not set — the app will fall back to mock data.'
  );
}

const content = `// Auto-generated by scripts/generate-env.js — do not edit manually.\nexport const API_KEY = '${apiKey}';\n`;

const outputPath = path.join(__dirname, '..', 'src', 'environments', 'environment.key.ts');
fs.writeFileSync(outputPath, content, 'utf8');

console.log('\u2705  environment.key.ts generated.');
